export const MODULE_IDENTIFICATOR = {
  USERS_MANAGE: "1",
  DOCTORS_MANAGE: "2",
  NURSE_MANAGE: "3",
  PATIENTS_INFO: "4",
  MEDICALS_INFO: "5",
  CR_EXAM_RESULT: "6",
  CR_SICKNESS: "7",
  CR_BIOLOGIC_FUNCTIONS: "8",
  CR_PATOLOGICAL_HISTORY: "9",
  CR_PHYSYCAL_EXAM: "10",
  CR_SYNDROMES_GERIATRIC: "11",
  CR_CLINICAL_ASSESSMENT: "12",
  CR_COMMENTARY: "13",
};

export const PERMISSION_TYPE = {
  CREATE: "create",
  MODIFY: "modify",
  VISUALIZE: "visualize",
};
