export const PATH = {
  root: "",
  dashboard: "/dashboard",
  administration: "/administration",
  error: "/error",
  address_not_found: "/address-not-found",
  new: "/new",
  detail: "/detail",
  login: "/login",
  users: "/users",
  doctors: "/doctors",
  nurses: "/nurses",
  patients: "/patients",
  clinicRecords: "/clinic-records",
  medicalInfo: "/medical-info",
  sickness:"/sickness",
  examResult: "/exam-result",
  biologicFunctions: "/biologic-functions",
  patologicalHistory: "/patological",
  physicalExam: "/physical-exam",
  syndromesGeriatric: "/syndromes",
  clinicalAssessment: "/clinical-assessment",
  commentary: "/commentary"
};
